# _config.yml

# Site Settings
title: ""
theme: jekyll-theme-cayman
baseurl: "/ADAWebsite"

markdown: kramdown

# Custom CSS for styling
include:
  - assets/css/style.css

plugins:
  - jekyll-seo-tag
  - jekyll-paginate